### ISSUE TITLE
Investigate potential memory leaks

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-logsene-android#20] opened 2020-04-06 12:49 UTC
From a user:

> On the memory leak, it seems the issue was more Android-related.
> 
> We only made three changes overall:
> 
> - Closing cursors after accessing the SQLite Database
> - ObjectDBHelper changed to static
> - Updated the okhttp dependency version
> 
> The issues were probably being caused by okhttp, but to be safe we made the aforementioned changes.
>

**Comment by otisg** [comment] 2020-04-13 20:48
From the same user:


SqliteObjectQueue.java:

1. changed ObjectDbHelper to static
public static class ObjectDbHelper extends SQLiteOpenHelper {

2. closed cursor on - public List<JSONObject> peek(int max){
...
c.close();
return results;
}

on build.gradle:
3. Changed okhttp version:

implementation 'com.squareup.okhttp3:okhttp:4.3.0'

(it worked for sematext but broke another part of our app, so we are currently testing with 3.12)

**Comment by gr0** [comment] 2020-04-24 11:33
The changes are now in master. I will release a new version of the library with them. The things that needed to be done is refactoring of the SQLLite usage, cursor closing and statements closing. After that profiling show that the memory usage is stable and no more leaks are reported.

**Comment by gr0** [comment] 2020-04-24 11:34
The commit that fixes the issue is: https://github.com/sematext/sematext-logsene-android/commit/0b59695ca68d1b5055fd46b45baddaf51a664c51

**Closed as completed** 2020-04-24 11:34 UTC
